config:
  # Allow long lines — tables and URLs often exceed 80 chars
  MD013: false
  # Allow duplicate headings in different files (templates reuse headings)
  MD024: false
  # Allow inline HTML (used in some prompts/templates)
  MD033: false
